print (" -")
print ("(  \ ")
print (" )  )  _""_ ")
print ("(  (  .    .  A.-.A")
print (" \  \/      \/ , , \ ")
print ("  \    \    =;  t  /")
print ("   \    |"".  .,__'   ")
print ("     / //  | ||")
print ("    /_,))  |_,))")